// Feature 7 projects

module.exports = [
  {
    name: "Backgammon",
    img: "backgammon.png",
    isDeployed: true,
    url: "https://matt-gross-27.github.io/backgammon/",
    repo: "https://github.com/matt-gross-27/backgammon",
    featured: true,
  },
  {
    name: "The Tech Blog",
    img: "the-tech-blog.png",
    isDeployed: true,
    url: "https://the-tech-blog-3000.herokuapp.com/",
    repo: "https://github.com/matt-gross-27/the-tech-blog",
    featured: true,
  },
  {
    name: "Flowers",
    img: "flowers.png",
    isDeployed: true,
    url: "https://send-flowers.herokuapp.com/",
    repo: "https://github.com/matt-gross-27/flowers",
    featured: true,
  },
  {
    name: "Trading News",
    img: "trading-news.png",
    isDeployed: true,
    url: "https://jitochadha1.github.io/trading-news/trending.html",
    repo: "https://github.com/jitochadha1/trading-news",
    featured: false,
  },
  {
    name: "Weather",
    img: "weather.png",
    isDeployed: true,
    url: "https://matt-gross-27.github.io/weather/",
    repo: "https://github.com/matt-gross-27/weather",
    featured: false,
  },
  {
    name: "Jest Another RPG",
    img: "jest-another-rpg.png",
    isDeployed: false,
    url: "",
    repo: "https://github.com/matt-gross-27/jest-another-RPG",
    featured: false,
  },
  {
    name: "Taskmaster Pro",
    img: "taskmaster-pro.png",
    isDeployed: true,
    url: "https://matt-gross-27.github.io/taskmaster-pro/",
    repo: "https://github.com/matt-gross-27/taskmaster-pro",
    featured: false,
  },
]